Traceback (most recent call last):
  File "/bigdata/users/postgrad/sramesh/Galaxy-Classification-ViT/labelling.py", line 29, in <module>
    df = pd.read_csv(csv_file)
  File "/bigdata/Software/python3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/bigdata/Software/python3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/bigdata/Software/python3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/bigdata/Software/python3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/bigdata/Software/python3.10/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/bigdata/Software/python3.10/lib/python3.10/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/galaxy_data.csv'
